name: lint
on:
  push:
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update
        run: |
          sudo apt-get update
          sudo apt-get upgrade 
      - name: deps
        run: sudo apt-get install shellcheck
      - name: lint
        run: make
