name: lint
on:
  push:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deps
        run: sudo apt-get install shellcheck
      - name: lint
        run: make
